name: API Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Newman and Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |
        newman run spotify_collection.json \
        -e spotify_env.json \
        -r cli,htmlextra \
        --reporter-htmlextra-export report.html

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: API-Test-Report
        path: report.html
